services:
  - type: web
    name: e-nose-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDir: backend
    envVars:
      - key: PORT
        value: 10000
